//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public long IDPlayer { get; set; }
        public string Names { get; set; }
        public string Surnames { get; set; }
        public string NickName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual Profiles Profiles { get; set; }
    }
}
