//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilesSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilesSet()
        {
            this.ProfilesSet1 = new HashSet<ProfilesSet>();
            this.ProfilesSet2 = new HashSet<ProfilesSet>();
            this.FriendRequestsSet = new HashSet<FriendRequestsSet>();
            this.FriendRequestsSet1 = new HashSet<FriendRequestsSet>();
        }
    
        public long IDProfile { get; set; }
        public Nullable<long> Score { get; set; }
        public string LoginStatus { get; set; }
        public string ProfileImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilesSet> ProfilesSet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilesSet> ProfilesSet2 { get; set; }
        public virtual PlayersSet PlayersSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequestsSet> FriendRequestsSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequestsSet> FriendRequestsSet1 { get; set; }
    }
}
