//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("RenovaciónLISDatabase", "ProfilesSetProfilesSet", "ProfilesSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.DatabaseManager.ProfilesSet), "ProfilesSet1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.DatabaseManager.ProfilesSet))]
[assembly: EdmRelationshipAttribute("RenovaciónLISDatabase", "PlayersSetProfilesSet", "PlayersSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.DatabaseManager.PlayersSet), "ProfilesSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.DatabaseManager.ProfilesSet))]
[assembly: EdmRelationshipAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet", "FriendRequestsSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.DatabaseManager.FriendRequestsSet), "ProfilesSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.DatabaseManager.ProfilesSet))]
[assembly: EdmRelationshipAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet1", "FriendRequestsSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.DatabaseManager.FriendRequestsSet), "ProfilesSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.DatabaseManager.ProfilesSet))]

#endregion

namespace Server.DatabaseManager
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class RenovaciónLISDatabaseContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto RenovaciónLISDatabaseContainer usando la cadena de conexión encontrada en la sección 'RenovaciónLISDatabaseContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public RenovaciónLISDatabaseContainer() : base("name=RenovaciónLISDatabaseContainer", "RenovaciónLISDatabaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto RenovaciónLISDatabaseContainer.
        /// </summary>
        public RenovaciónLISDatabaseContainer(string connectionString) : base(connectionString, "RenovaciónLISDatabaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto RenovaciónLISDatabaseContainer.
        /// </summary>
        public RenovaciónLISDatabaseContainer(EntityConnection connection) : base(connection, "RenovaciónLISDatabaseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FriendRequestsSet> FriendRequestsSetSet
        {
            get
            {
                if ((_FriendRequestsSetSet == null))
                {
                    _FriendRequestsSetSet = base.CreateObjectSet<FriendRequestsSet>("FriendRequestsSetSet");
                }
                return _FriendRequestsSetSet;
            }
        }
        private ObjectSet<FriendRequestsSet> _FriendRequestsSetSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ProfilesSet> ProfilesSetSet
        {
            get
            {
                if ((_ProfilesSetSet == null))
                {
                    _ProfilesSetSet = base.CreateObjectSet<ProfilesSet>("ProfilesSetSet");
                }
                return _ProfilesSetSet;
            }
        }
        private ObjectSet<ProfilesSet> _ProfilesSetSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PlayersSet> PlayersSetSet
        {
            get
            {
                if ((_PlayersSetSet == null))
                {
                    _PlayersSetSet = base.CreateObjectSet<PlayersSet>("PlayersSetSet");
                }
                return _PlayersSetSet;
            }
        }
        private ObjectSet<PlayersSet> _PlayersSetSet;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FriendRequestsSetSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFriendRequestsSetSet(FriendRequestsSet friendRequestsSet)
        {
            base.AddObject("FriendRequestsSetSet", friendRequestsSet);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProfilesSetSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProfilesSetSet(ProfilesSet profilesSet)
        {
            base.AddObject("ProfilesSetSet", profilesSet);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PlayersSetSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPlayersSetSet(PlayersSet playersSet)
        {
            base.AddObject("PlayersSetSet", playersSet);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RenovaciónLISDatabase", Name="FriendRequestsSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FriendRequestsSet : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FriendRequestsSet.
        /// </summary>
        /// <param name="iDFriendRequest">Valor inicial de la propiedad IDFriendRequest.</param>
        /// <param name="message">Valor inicial de la propiedad Message.</param>
        /// <param name="creationDate">Valor inicial de la propiedad CreationDate.</param>
        /// <param name="sendingStatus">Valor inicial de la propiedad SendingStatus.</param>
        /// <param name="aceptationStatus">Valor inicial de la propiedad AceptationStatus.</param>
        public static FriendRequestsSet CreateFriendRequestsSet(global::System.Int64 iDFriendRequest, global::System.String message, global::System.DateTime creationDate, global::System.String sendingStatus, global::System.String aceptationStatus)
        {
            FriendRequestsSet friendRequestsSet = new FriendRequestsSet();
            friendRequestsSet.IDFriendRequest = iDFriendRequest;
            friendRequestsSet.Message = message;
            friendRequestsSet.CreationDate = creationDate;
            friendRequestsSet.SendingStatus = sendingStatus;
            friendRequestsSet.AceptationStatus = aceptationStatus;
            return friendRequestsSet;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDFriendRequest
        {
            get
            {
                return _IDFriendRequest;
            }
            set
            {
                if (_IDFriendRequest != value)
                {
                    OnIDFriendRequestChanging(value);
                    ReportPropertyChanging("IDFriendRequest");
                    _IDFriendRequest = StructuralObject.SetValidValue(value, "IDFriendRequest");
                    ReportPropertyChanged("IDFriendRequest");
                    OnIDFriendRequestChanged();
                }
            }
        }
        private global::System.Int64 _IDFriendRequest;
        partial void OnIDFriendRequestChanging(global::System.Int64 value);
        partial void OnIDFriendRequestChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value, "CreationDate");
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SendingStatus
        {
            get
            {
                return _SendingStatus;
            }
            set
            {
                OnSendingStatusChanging(value);
                ReportPropertyChanging("SendingStatus");
                _SendingStatus = StructuralObject.SetValidValue(value, false, "SendingStatus");
                ReportPropertyChanged("SendingStatus");
                OnSendingStatusChanged();
            }
        }
        private global::System.String _SendingStatus;
        partial void OnSendingStatusChanging(global::System.String value);
        partial void OnSendingStatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AceptationStatus
        {
            get
            {
                return _AceptationStatus;
            }
            set
            {
                OnAceptationStatusChanging(value);
                ReportPropertyChanging("AceptationStatus");
                _AceptationStatus = StructuralObject.SetValidValue(value, false, "AceptationStatus");
                ReportPropertyChanged("AceptationStatus");
                OnAceptationStatusChanged();
            }
        }
        private global::System.String _AceptationStatus;
        partial void OnAceptationStatusChanging(global::System.String value);
        partial void OnAceptationStatusChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet", "ProfilesSet")]
        public ProfilesSet ProfilesSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "ProfilesSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "ProfilesSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProfilesSet> ProfilesSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "ProfilesSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "ProfilesSet", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet1", "ProfilesSet")]
        public ProfilesSet ProfilesSet1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "ProfilesSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "ProfilesSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProfilesSet> ProfilesSet1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "ProfilesSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProfilesSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "ProfilesSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RenovaciónLISDatabase", Name="PlayersSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlayersSet : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PlayersSet.
        /// </summary>
        /// <param name="iDPlayer">Valor inicial de la propiedad IDPlayer.</param>
        /// <param name="names">Valor inicial de la propiedad Names.</param>
        /// <param name="surnames">Valor inicial de la propiedad Surnames.</param>
        /// <param name="nickName">Valor inicial de la propiedad NickName.</param>
        /// <param name="birthDate">Valor inicial de la propiedad BirthDate.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        /// <param name="password">Valor inicial de la propiedad Password.</param>
        public static PlayersSet CreatePlayersSet(global::System.Int64 iDPlayer, global::System.String names, global::System.String surnames, global::System.String nickName, global::System.DateTime birthDate, global::System.String email, global::System.String password)
        {
            PlayersSet playersSet = new PlayersSet();
            playersSet.IDPlayer = iDPlayer;
            playersSet.Names = names;
            playersSet.Surnames = surnames;
            playersSet.NickName = nickName;
            playersSet.BirthDate = birthDate;
            playersSet.Email = email;
            playersSet.Password = password;
            return playersSet;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDPlayer
        {
            get
            {
                return _IDPlayer;
            }
            set
            {
                if (_IDPlayer != value)
                {
                    OnIDPlayerChanging(value);
                    ReportPropertyChanging("IDPlayer");
                    _IDPlayer = StructuralObject.SetValidValue(value, "IDPlayer");
                    ReportPropertyChanged("IDPlayer");
                    OnIDPlayerChanged();
                }
            }
        }
        private global::System.Int64 _IDPlayer;
        partial void OnIDPlayerChanging(global::System.Int64 value);
        partial void OnIDPlayerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Names
        {
            get
            {
                return _Names;
            }
            set
            {
                OnNamesChanging(value);
                ReportPropertyChanging("Names");
                _Names = StructuralObject.SetValidValue(value, false, "Names");
                ReportPropertyChanged("Names");
                OnNamesChanged();
            }
        }
        private global::System.String _Names;
        partial void OnNamesChanging(global::System.String value);
        partial void OnNamesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Surnames
        {
            get
            {
                return _Surnames;
            }
            set
            {
                OnSurnamesChanging(value);
                ReportPropertyChanging("Surnames");
                _Surnames = StructuralObject.SetValidValue(value, false, "Surnames");
                ReportPropertyChanged("Surnames");
                OnSurnamesChanged();
            }
        }
        private global::System.String _Surnames;
        partial void OnSurnamesChanging(global::System.String value);
        partial void OnSurnamesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false, "NickName");
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value, "BirthDate");
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private global::System.DateTime _BirthDate;
        partial void OnBirthDateChanging(global::System.DateTime value);
        partial void OnBirthDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "PlayersSetProfilesSet", "ProfilesSet")]
        public ProfilesSet ProfilesSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "ProfilesSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "ProfilesSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProfilesSet> ProfilesSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProfilesSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "ProfilesSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProfilesSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "ProfilesSet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RenovaciónLISDatabase", Name="ProfilesSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProfilesSet : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ProfilesSet.
        /// </summary>
        /// <param name="iDProfile">Valor inicial de la propiedad IDProfile.</param>
        /// <param name="loginStatus">Valor inicial de la propiedad LoginStatus.</param>
        public static ProfilesSet CreateProfilesSet(global::System.Int64 iDProfile, global::System.String loginStatus)
        {
            ProfilesSet profilesSet = new ProfilesSet();
            profilesSet.IDProfile = iDProfile;
            profilesSet.LoginStatus = loginStatus;
            return profilesSet;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDProfile
        {
            get
            {
                return _IDProfile;
            }
            set
            {
                if (_IDProfile != value)
                {
                    OnIDProfileChanging(value);
                    ReportPropertyChanging("IDProfile");
                    _IDProfile = StructuralObject.SetValidValue(value, "IDProfile");
                    ReportPropertyChanged("IDProfile");
                    OnIDProfileChanged();
                }
            }
        }
        private global::System.Int64 _IDProfile;
        partial void OnIDProfileChanging(global::System.Int64 value);
        partial void OnIDProfileChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value, "Score");
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private Nullable<global::System.Int64> _Score;
        partial void OnScoreChanging(Nullable<global::System.Int64> value);
        partial void OnScoreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginStatus
        {
            get
            {
                return _LoginStatus;
            }
            set
            {
                OnLoginStatusChanging(value);
                ReportPropertyChanging("LoginStatus");
                _LoginStatus = StructuralObject.SetValidValue(value, false, "LoginStatus");
                ReportPropertyChanged("LoginStatus");
                OnLoginStatusChanged();
            }
        }
        private global::System.String _LoginStatus;
        partial void OnLoginStatusChanging(global::System.String value);
        partial void OnLoginStatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfileImage
        {
            get
            {
                return _ProfileImage;
            }
            set
            {
                OnProfileImageChanging(value);
                ReportPropertyChanging("ProfileImage");
                _ProfileImage = StructuralObject.SetValidValue(value, true, "ProfileImage");
                ReportPropertyChanged("ProfileImage");
                OnProfileImageChanged();
            }
        }
        private global::System.String _ProfileImage;
        partial void OnProfileImageChanging(global::System.String value);
        partial void OnProfileImageChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "ProfilesSetProfilesSet", "ProfilesSet1")]
        public EntityCollection<ProfilesSet> ProfilesSet1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProfilesSet>("RenovaciónLISDatabase.ProfilesSetProfilesSet", "ProfilesSet1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProfilesSet>("RenovaciónLISDatabase.ProfilesSetProfilesSet", "ProfilesSet1", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "ProfilesSetProfilesSet", "ProfilesSet")]
        public EntityCollection<ProfilesSet> ProfilesSet2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProfilesSet>("RenovaciónLISDatabase.ProfilesSetProfilesSet", "ProfilesSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProfilesSet>("RenovaciónLISDatabase.ProfilesSetProfilesSet", "ProfilesSet", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "PlayersSetProfilesSet", "PlayersSet")]
        public PlayersSet PlayersSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayersSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "PlayersSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayersSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "PlayersSet").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PlayersSet> PlayersSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayersSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "PlayersSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PlayersSet>("RenovaciónLISDatabase.PlayersSetProfilesSet", "PlayersSet", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet", "FriendRequestsSet")]
        public EntityCollection<FriendRequestsSet> FriendRequestsSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendRequestsSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "FriendRequestsSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendRequestsSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet", "FriendRequestsSet", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RenovaciónLISDatabase", "FriendRequestsSetProfilesSet1", "FriendRequestsSet")]
        public EntityCollection<FriendRequestsSet> FriendRequestsSet1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendRequestsSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "FriendRequestsSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendRequestsSet>("RenovaciónLISDatabase.FriendRequestsSetProfilesSet1", "FriendRequestsSet", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
