//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public long IDPlayer { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public string NickName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> BirthDay { get; set; }
        public string BirthMonth { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public string MainEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string Password { get; set; }
    
        public virtual Profiles Profiles { get; set; }
    }
}
