//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceProfileForCallbackMethodsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProfileForCallbackMethodsReference.IProfileCallbackMethods", CallbackContract=typeof(Client.ServiceProfileForCallbackMethodsReference.IProfileCallbackMethodsCallback))]
    public interface IProfileCallbackMethods {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/Connect")]
        void Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/Connect")]
        System.Threading.Tasks.Task ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/Disconnect")]
        void Disconnect(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/InviteFriendToTheLobby")]
        void InviteFriendToTheLobby(string friendNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/InviteFriendToTheLobby")]
        System.Threading.Tasks.Task InviteFriendToTheLobbyAsync(string friendNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/UpdateFriendsListsToAllConnectedClient" +
            "s")]
        void UpdateFriendsListsToAllConnectedClients();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/UpdateFriendsListsToAllConnectedClient" +
            "s")]
        System.Threading.Tasks.Task UpdateFriendsListsToAllConnectedClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileCallbackMethodsCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/UpdateFriendsLists")]
        void UpdateFriendsLists();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/UpdateFriendsForInviteLists")]
        void UpdateFriendsForInviteLists();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileCallbackMethods/OpenPaneForEnterTheLobby")]
        void OpenPaneForEnterTheLobby();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileCallbackMethodsChannel : Client.ServiceProfileForCallbackMethodsReference.IProfileCallbackMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileCallbackMethodsClient : System.ServiceModel.DuplexClientBase<Client.ServiceProfileForCallbackMethodsReference.IProfileCallbackMethods>, Client.ServiceProfileForCallbackMethodsReference.IProfileCallbackMethods {
        
        public ProfileCallbackMethodsClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProfileCallbackMethodsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProfileCallbackMethodsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileCallbackMethodsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileCallbackMethodsClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string username) {
            base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public void Disconnect(string username) {
            base.Channel.Disconnect(username);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string username) {
            return base.Channel.DisconnectAsync(username);
        }
        
        public void InviteFriendToTheLobby(string friendNickname) {
            base.Channel.InviteFriendToTheLobby(friendNickname);
        }
        
        public System.Threading.Tasks.Task InviteFriendToTheLobbyAsync(string friendNickname) {
            return base.Channel.InviteFriendToTheLobbyAsync(friendNickname);
        }
        
        public void UpdateFriendsListsToAllConnectedClients() {
            base.Channel.UpdateFriendsListsToAllConnectedClients();
        }
        
        public System.Threading.Tasks.Task UpdateFriendsListsToAllConnectedClientsAsync() {
            return base.Channel.UpdateFriendsListsToAllConnectedClientsAsync();
        }
    }
}
