//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renovación_LIS_Client.ServiceMultiplayerCrosswordReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMultiplayerCrosswordReference.IMultiplayerCrossword")]
    public interface IMultiplayerCrossword {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiplayerCrossword/GetStrings", ReplyAction="http://tempuri.org/IMultiplayerCrossword/GetStringsResponse")]
        string[] GetStrings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiplayerCrossword/GetStrings", ReplyAction="http://tempuri.org/IMultiplayerCrossword/GetStringsResponse")]
        System.Threading.Tasks.Task<string[]> GetStringsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMultiplayerCrosswordChannel : Renovación_LIS_Client.ServiceMultiplayerCrosswordReference.IMultiplayerCrossword, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiplayerCrosswordClient : System.ServiceModel.ClientBase<Renovación_LIS_Client.ServiceMultiplayerCrosswordReference.IMultiplayerCrossword>, Renovación_LIS_Client.ServiceMultiplayerCrosswordReference.IMultiplayerCrossword {
        
        public MultiplayerCrosswordClient() {
        }
        
        public MultiplayerCrosswordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MultiplayerCrosswordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiplayerCrosswordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiplayerCrosswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetStrings() {
            return base.Channel.GetStrings();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStringsAsync() {
            return base.Channel.GetStringsAsync();
        }
    }
}
