//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renovación_LIS_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renovación_LIS_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Course that addresses legal aspects related to the technology.
        /// </summary>
        public static string _1__Course_that_addresses_legal_aspects_related_to_the_technology {
            get {
                return ResourceManager.GetString("1. Course that addresses legal aspects related to the technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Data source that provides information for an application.
        /// </summary>
        public static string _1__Data_source_that_provides_information_for_an_application {
            get {
                return ResourceManager.GetString("1. Data source that provides information for an application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Data structure that follows the FIFO principle.
        /// </summary>
        public static string _1__Data_structure_that_follows_the_FIFO_principle {
            get {
                return ResourceManager.GetString("1. Data structure that follows the FIFO principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Practices to avoid during programming.
        /// </summary>
        public static string _1__Practices_to_avoid_during_programming {
            get {
                return ResourceManager.GetString("1. Practices to avoid during programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Statement used in databases to retrieve data.
        /// </summary>
        public static string _1__Statement_used_in_databases_to_retrieve_data {
            get {
                return ResourceManager.GetString("1. Statement used in databases to retrieve data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. High-level programming language known for its simplicity and readability.
        /// </summary>
        public static string _2__High_level_programming_language_known_for_its_simplicity_and_readability {
            get {
                return ResourceManager.GetString("2. High-level programming language known for its simplicity and readability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Key programming paradigm in Software Engineering.
        /// </summary>
        public static string _2__Key_programming_paradigm_in_Software_Engineering {
            get {
                return ResourceManager.GetString("2. Key programming paradigm in Software Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Measurement of the complexity of a program based on its control structure.
        /// </summary>
        public static string _2__Measurement_of_the_complexity_of_a_program_based_on_its_control_structure {
            get {
                return ResourceManager.GetString("2. Measurement of the complexity of a program based on its control structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Model to represent the logical structure of a database.
        /// </summary>
        public static string _2__Model_to_represent_the_logical_structure_of_a_database {
            get {
                return ResourceManager.GetString("2. Model to represent the logical structure of a database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Visual component that allows interaction with a program.
        /// </summary>
        public static string _2__Visual_component_that_allows_interaction_with_a_program {
            get {
                return ResourceManager.GetString("2. Visual component that allows interaction with a program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Educational center for software engineering.
        /// </summary>
        public static string _3__Educational_center_for_software_engineering {
            get {
                return ResourceManager.GetString("3. Educational center for software engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. High-level programming language known for its simplicity and readability.
        /// </summary>
        public static string _3__High_level_programming_language_known_for_its_simplicity_and_readability {
            get {
                return ResourceManager.GetString("3. High-level programming language known for its simplicity and readability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Process of creating and developing software.
        /// </summary>
        public static string _3__Process_of_creating_and_developing_software {
            get {
                return ResourceManager.GetString("3. Process of creating and developing software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Repetitive control structure.
        /// </summary>
        public static string _3__Repetitive_control_structure {
            get {
                return ResourceManager.GetString("3. Repetitive control structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Statement used in databases to retrieve data.
        /// </summary>
        public static string _3__Statement_used_in_databases_to_retrieve_data {
            get {
                return ResourceManager.GetString("3. Statement used in databases to retrieve data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. Course that addresses legal aspects related to the technology.
        /// </summary>
        public static string _4__Course_that_addresses_legal_aspects_related_to_the_technology {
            get {
                return ResourceManager.GetString("4. Course that addresses legal aspects related to the technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. Markup language for creating web pages.
        /// </summary>
        public static string _4__Markup_language_for_creating_web_pages {
            get {
                return ResourceManager.GetString("4. Markup language for creating web pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. Process of obtaining and documenting the requirements of a system.
        /// </summary>
        public static string _4__Process_of_obtaining_and_documenting_the_requirements_of_a_system {
            get {
                return ResourceManager.GetString("4. Process of obtaining and documenting the requirements of a system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. Teacher who has Sun Certified Java Programmer.
        /// </summary>
        public static string _4__Teacher_who_has_Sun_Certified_Java_Programmer {
            get {
                return ResourceManager.GetString("4. Teacher who has Sun Certified Java Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Condition-based repetitive control structure.
        /// </summary>
        public static string _5__Condition_based_repetitive_control_structure {
            get {
                return ResourceManager.GetString("5. Condition-based repetitive control structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Open source operating system.
        /// </summary>
        public static string _5__Open_source_operating_system {
            get {
                return ResourceManager.GetString("5. Open source operating system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Popular integrated development environment for various languages.
        /// </summary>
        public static string _5__Popular_integrated_development_environment_for_various_languages {
            get {
                return ResourceManager.GetString("5. Popular integrated development environment for various languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Professor who has a Master&apos;s Degree in Free Software at the Open University of Catalonia.
        /// </summary>
        public static string _5__Professor_who_has_a_Master_s_Degree_in_Free_Software_at_the_Open_University_of_Catalonia {
            get {
                return ResourceManager.GetString("5. Professor who has a Master\'s Degree in Free Software at the Open University of" +
                        " Catalonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. Widely used Integrated Development Environment for java.
        /// </summary>
        public static string _5__Widely_used_Integrated_Development_Environment_for_java {
            get {
                return ResourceManager.GetString("5. Widely used Integrated Development Environment for java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Fundamental skill set and concepts in computer science.
        /// </summary>
        public static string _6__Fundamental_skill_set_and_concepts_in_computer_science {
            get {
                return ResourceManager.GetString("6. Fundamental skill set and concepts in computer science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Hosting and version control platform for collaborative development.
        /// </summary>
        public static string _6__Hosting_and_version_control_platform_for_collaborative_development {
            get {
                return ResourceManager.GetString("6. Hosting and version control platform for collaborative development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Integrated Development Environment (IDE) widely used for java.
        /// </summary>
        public static string _6__Integrated_Development_Environment__IDE__widely_used_for_java {
            get {
                return ResourceManager.GetString("6. Integrated Development Environment (IDE) widely used for java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Integrated development environment for Java.
        /// </summary>
        public static string _6__Integrated_development_environment_for_Java {
            get {
                return ResourceManager.GetString("6. Integrated development environment for Java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6. Linear and dynamic data structures.
        /// </summary>
        public static string _6__Linear_and_dynamic_data_structures {
            get {
                return ResourceManager.GetString("6. Linear and dynamic data structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7. Software development methodology that uses interaction diagrams.
        /// </summary>
        public static string _7__Software_development_methodology_that_uses_interaction_diagrams {
            get {
                return ResourceManager.GetString("7. Software development methodology that uses interaction diagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7. Visual component that allows interaction with a program.
        /// </summary>
        public static string _7__Visual_component_that_allows_interaction_with_a_program {
            get {
                return ResourceManager.GetString("7. Visual component that allows interaction with a program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8. Programming language for web development server side.
        /// </summary>
        public static string _8__Programming_language_for_web_development_server_side {
            get {
                return ResourceManager.GetString("8. Programming language for web development server side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code has been sent to your email.
        /// </summary>
        public static string A_code_has_been_sent_to_your_email {
            get {
                return ResourceManager.GetString("A code has been sent to your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept friend request.
        /// </summary>
        public static string Accept_friend_request {
            get {
                return ResourceManager.GetString("Accept friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account made successfully!!!.
        /// </summary>
        public static string Account_made_successfully {
            get {
                return ResourceManager.GetString("Account made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a And the selected crossword is:.
        /// </summary>
        public static string And_the_selected_crossword_is_ {
            get {
                return ResourceManager.GetString("And the selected crossword is:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure?.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to accept the friend request?.
        /// </summary>
        public static string Are_you_sure_you_want_to_accept_the_friend_request_ {
            get {
                return ResourceManager.GetString("Are you sure you want to accept the friend request?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the friend request sending?.
        /// </summary>
        public static string Are_you_sure_you_want_to_cancel_the_friend_request_sending_ {
            get {
                return ResourceManager.GetString("Are you sure you want to cancel the friend request sending?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the friendship?.
        /// </summary>
        public static string Are_you_sure_you_want_to_cancel_the_friendship_ {
            get {
                return ResourceManager.GetString("Are you sure you want to cancel the friendship?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to invite this friend?.
        /// </summary>
        public static string Are_you_sure_you_want_to_invite_this_friend_ {
            get {
                return ResourceManager.GetString("Are you sure you want to invite this friend?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reject the friend request?.
        /// </summary>
        public static string Are_you_sure_you_want_to_reject_the_friend_request_ {
            get {
                return ResourceManager.GetString("Are you sure you want to reject the friend request?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ban.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banned players.
        /// </summary>
        public static string Banned_players {
            get {
                return ResourceManager.GetString("Banned players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth date should be before than the actual date.
        /// </summary>
        public static string Birth_date_should_be_before_than_the_actual_date {
            get {
                return ResourceManager.GetString("Birth date should be before than the actual date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to menu.
        /// </summary>
        public static string BackMenu {
            get {
                return ResourceManager.GetString("BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth day.
        /// </summary>
        public static string Birth_day {
            get {
                return ResourceManager.GetString("Birth day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel friend request.
        /// </summary>
        public static string Cancel_friend_request {
            get {
                return ResourceManager.GetString("Cancel friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel friendship.
        /// </summary>
        public static string Cancel_friendship {
            get {
                return ResourceManager.GetString("Cancel friendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelation of friend request send made sucessfully.
        /// </summary>
        public static string Cancelation_of_friend_request_send_made_sucessfully {
            get {
                return ResourceManager.GetString("Cancelation of friend request send made sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancellation of sending friend request made successfully!!!.
        /// </summary>
        public static string Cancellation_of_sending_friend_request_made_successfully {
            get {
                return ResourceManager.GetString("Cancellation of sending friend request made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a level.
        /// </summary>
        public static string Choose_a_level {
            get {
                return ResourceManager.GetString("Choose a level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing....
        /// </summary>
        public static string Closing___ {
            get {
                return ResourceManager.GetString("Closing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code for change your password..
        /// </summary>
        public static string Code_for_change_your_password {
            get {
                return ResourceManager.GetString("Code for change your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your level.
        /// </summary>
        public static string ChooseYourLevel {
            get {
                return ResourceManager.GetString("ChooseYourLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You passed the level:.
        /// </summary>
        public static string CompleteLevel {
            get {
                return ResourceManager.GetString("CompleteLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your new password.
        /// </summary>
        public static string Confirm_your_new_password {
            get {
                return ResourceManager.GetString("Confirm your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date.
        /// </summary>
        public static string Creation_date {
            get {
                return ResourceManager.GetString("Creation date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crystal saloon.
        /// </summary>
        public static string Crystal_saloon {
            get {
                return ResourceManager.GetString("Crystal saloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to ban this player?.
        /// </summary>
        public static string Do_you_want_to_ban_this_player_ {
            get {
                return ResourceManager.GetString("Do you want to ban this player?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to enter to the lobby?.
        /// </summary>
        public static string Do_you_want_to_enter_to_the_lobby_ {
            get {
                return ResourceManager.GetString("Do you want to enter to the lobby?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to exit?.
        /// </summary>
        public static string Do_you_want_to_exit {
            get {
                return ResourceManager.GetString("Do you want to exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to set admin to this player?.
        /// </summary>
        public static string Do_you_want_to_set_admin_to_this_player_ {
            get {
                return ResourceManager.GetString("Do you want to set admin to this player?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to unban this player?.
        /// </summary>
        public static string Do_you_want_to_unban_this_player_ {
            get {
                return ResourceManager.GetString("Do you want to unban this player?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctorated in CS.
        /// </summary>
        public static string Doctorated_in_CS {
            get {
                return ResourceManager.GetString("Doctorated in CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next level:.
        /// </summary>
        public static string ContinueLevel {
            get {
                return ResourceManager.GetString("ContinueLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Account.
        /// </summary>
        public static string ECONEX_bathroom_low_level {
            get {
                return ResourceManager.GetString("ECONEX bathroom low level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email already on use.
        /// </summary>
        public static string Email_already_on_use {
            get {
                return ResourceManager.GetString("Email already on use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email not found.
        /// </summary>
        public static string Email_not_found {
            get {
                return ResourceManager.GetString("Email not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Last Name.
        /// </summary>
        public static string First_Last_Name {
            get {
                return ResourceManager.GetString("First Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First place.
        /// </summary>
        public static string First_place {
            get {
                return ResourceManager.GetString("First place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fourth place.
        /// </summary>
        public static string Fourth_place {
            get {
                return ResourceManager.GetString("Fourth place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend nickname.
        /// </summary>
        public static string Friend_nickname {
            get {
                return ResourceManager.GetString("Friend nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request rejected.
        /// </summary>
        public static string Friend_request_rejected {
            get {
                return ResourceManager.GetString("Friend request rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent succesfully!!!.
        /// </summary>
        public static string Friend_request_sent_succesfully {
            get {
                return ResourceManager.GetString("Friend request sent succesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request successfully accepted!!!.
        /// </summary>
        public static string Friend_request_successfully_accepted {
            get {
                return ResourceManager.GetString("Friend request successfully accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends requests.
        /// </summary>
        public static string Friends_requests {
            get {
                return ResourceManager.GetString("Friends requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends that you can invite.
        /// </summary>
        public static string Friends_that_you_can_invite {
            get {
                return ResourceManager.GetString("Friends that you can invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship cancellation made successfully.
        /// </summary>
        public static string Friendship_cancellation_made_successfully {
            get {
                return ResourceManager.GetString("Friendship cancellation made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go!.
        /// </summary>
        public static string Go_ {
            get {
                return ResourceManager.GetString("Go!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has joined to the chat..
        /// </summary>
        public static string Has_joined_to_the_chat {
            get {
                return ResourceManager.GetString("Has joined to the chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you already have an account? Log In.
        /// </summary>
        public static string Have_you_already_have_an_account {
            get {
                return ResourceManager.GetString("Have you already have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect answer.
        /// </summary>
        public static string Incorrect_answer {
            get {
                return ResourceManager.GetString("Incorrect answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce the code.
        /// </summary>
        public static string Introduce_the_code {
            get {
                return ResourceManager.GetString("Introduce the code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce this code for change your password: .
        /// </summary>
        public static string Introduce_this_code_for_change_your_password {
            get {
                return ResourceManager.GetString("Introduce this code for change your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce your email.
        /// </summary>
        public static string Introduce_your_email {
            get {
                return ResourceManager.GetString("Introduce your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid code.
        /// </summary>
        public static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid nickname.
        /// </summary>
        public static string Invalid_nickname {
            get {
                return ResourceManager.GetString("Invalid nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation details.
        /// </summary>
        public static string Invitation_details {
            get {
                return ResourceManager.GetString("Invitation details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent successfully!.
        /// </summary>
        public static string Invitation_sent_successfully_ {
            get {
                return ResourceManager.GetString("Invitation sent successfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string Invite_friends {
            get {
                return ResourceManager.GetString("Invite friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a left the chat..
        /// </summary>
        public static string Left_the_chat {
            get {
                return ResourceManager.GetString("Left the chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make admin.
        /// </summary>
        public static string Make_admin {
            get {
                return ResourceManager.GetString("Make admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string Modify_profile {
            get {
                return ResourceManager.GetString("Modify profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string ModifyProfile {
            get {
                return ResourceManager.GetString("ModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplayer.
        /// </summary>
        public static string Multiplayer {
            get {
                return ResourceManager.GetString("Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music volume.
        /// </summary>
        public static string Music_volume {
            get {
                return ResourceManager.GetString("Music volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name(s).
        /// </summary>
        public static string Name_s_ {
            get {
                return ResourceManager.GetString("Name(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname already on use.
        /// </summary>
        public static string Nickname_already_on_use {
            get {
                return ResourceManager.GetString("Nickname already on use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not register yet? Sign Up.
        /// </summary>
        public static string NotregisterYet {
            get {
                return ResourceManager.GetString("NotregisterYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orientation.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed sucessfully!!!.
        /// </summary>
        public static string Password_changed_sucessfully___ {
            get {
                return ResourceManager.GetString("Password changed sucessfully!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player banned successfully!.
        /// </summary>
        public static string Player_banned_successfully_ {
            get {
                return ResourceManager.GetString("Player banned successfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player unbanned!.
        /// </summary>
        public static string Player_unbanned_ {
            get {
                return ResourceManager.GetString("Player unbanned!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile modified successfully!!!.
        /// </summary>
        public static string Profile_modified_successfully___ {
            get {
                return ResourceManager.GetString("Profile modified successfully!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile picture.
        /// </summary>
        public static string Profile_picture {
            get {
                return ResourceManager.GetString("Profile picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Image.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject friend request.
        /// </summary>
        public static string Reject_friend_request {
            get {
                return ResourceManager.GetString("Reject friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second place.
        /// </summary>
        public static string Second_place {
            get {
                return ResourceManager.GetString("Second place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a column or a row first.
        /// </summary>
        public static string Select_a_column_or_a_row_first {
            get {
                return ResourceManager.GetString("Select a column or a row first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an image.
        /// </summary>
        public static string Select_an_image {
            get {
                return ResourceManager.GetString("Select an image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected word:.
        /// </summary>
        public static string Selected_word_ {
            get {
                return ResourceManager.GetString("Selected word:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string Send_code {
            get {
                return ResourceManager.GetString("Send code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send invitation to friend.
        /// </summary>
        public static string Send_invitation_to_friend {
            get {
                return ResourceManager.GetString("Send invitation to friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send message.
        /// </summary>
        public static string Send_message {
            get {
                return ResourceManager.GetString("Send message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Should be in the lobby 2-4 players to start the game.
        /// </summary>
        public static string Should_be_in_the_lobby_2_4_players_to_start_the_game {
            get {
                return ResourceManager.GetString("Should be in the lobby 2-4 players to start the game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show friends invitations.
        /// </summary>
        public static string Show_friends_invitations {
            get {
                return ResourceManager.GetString("Show friends invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Singleplayer.
        /// </summary>
        public static string Singleplayer {
            get {
                return ResourceManager.GetString("Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Volume.
        /// </summary>
        public static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victory!.
        /// </summary>
        public static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congrats! you have passed the level, but this is not the end continue renovating the LIS.
        /// </summary>
        public static string VictoryMessage {
            get {
                return ResourceManager.GetString("VictoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success!!!.
        /// </summary>
        public static string Success___ {
            get {
                return ResourceManager.GetString("Success!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname(s).
        /// </summary>
        public static string Surname_s_ {
            get {
                return ResourceManager.GetString("Surname(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That player now is admin!.
        /// </summary>
        public static string That_player_now_is_admin_ {
            get {
                return ResourceManager.GetString("That player now is admin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file shouldn&apos;t be larger than 1 MB.
        /// </summary>
        public static string The_file_shouldn_t_be_larger_than_1_MB {
            get {
                return ResourceManager.GetString("The file shouldn\'t be larger than 1 MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game already has started!.
        /// </summary>
        public static string The_game_already_has_started_ {
            get {
                return ResourceManager.GetString("The game already has started!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The introduced nickname doesn&apos;t exists.
        /// </summary>
        public static string The_introduced_nickname_doesn_t_exists {
            get {
                return ResourceManager.GetString("The introduced nickname doesn\'t exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobby is full!!!.
        /// </summary>
        public static string The_lobby_is_full___ {
            get {
                return ResourceManager.GetString("The lobby is full!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The message shouldn&apos;t have more than 100 characters.
        /// </summary>
        public static string The_message_shouldn_t_have_more_than_100_characters {
            get {
                return ResourceManager.GetString("The message shouldn\'t have more than 100 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The message shouldn&apos;t have more than 80 characters.
        /// </summary>
        public static string The_message_shouldn_t_have_more_than_80_characters {
            get {
                return ResourceManager.GetString("The message shouldn\'t have more than 80 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password isn&apos;t correct.
        /// </summary>
        public static string The_password_isn_t_correct {
            get {
                return ResourceManager.GetString("The password isn\'t correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords aren&apos;t the same.
        /// </summary>
        public static string The_passwords_aren_t_the_same {
            get {
                return ResourceManager.GetString("The passwords aren\'t the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The text fields with invalid values are: .
        /// </summary>
        public static string The_text_fields_with_invalid_values_are {
            get {
                return ResourceManager.GetString("The text fields with invalid values are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is already logged.
        /// </summary>
        public static string The_user_is_already_logged {
            get {
                return ResourceManager.GetString("The user is already logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you want to send a friendrequest already has sent a friendrequest to you..
        /// </summary>
        public static string The_user_you_want_to_send_a_friendrequest_already_has_sent_a_friendrequest_to_you {
            get {
                return ResourceManager.GetString("The user you want to send a friendrequest already has sent a friendrequest to you" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you want to sent a friend request doesn&apos;t exists.
        /// </summary>
        public static string The_user_you_want_to_sent_a_friend_request_doesn_t_exists {
            get {
                return ResourceManager.GetString("The user you want to sent a friend request doesn\'t exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The word has already been answered, please select another one.
        /// </summary>
        public static string The_word_has_already_been_answered__please_select_another_one {
            get {
                return ResourceManager.GetString("The word has already been answered, please select another one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Third place.
        /// </summary>
        public static string Third_place {
            get {
                return ResourceManager.GetString("Third place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Times up!.
        /// </summary>
        public static string Times_up_ {
            get {
                return ResourceManager.GetString("Times up!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To confirm the new password, we&apos;ll send a code to your email.
        /// </summary>
        public static string To_confirm_the_new_password__we_ll_send_a_code_to_your_email {
            get {
                return ResourceManager.GetString("To confirm the new password, we\'ll send a code to your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too Bad!!!.
        /// </summary>
        public static string Too_Bad___ {
            get {
                return ResourceManager.GetString("Too Bad!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uh oh!.
        /// </summary>
        public static string Uh_oh_ {
            get {
                return ResourceManager.GetString("Uh oh!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unban.
        /// </summary>
        public static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify answer.
        /// </summary>
        public static string Verify_answer {
            get {
                return ResourceManager.GetString("Verify answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome back!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome back .
        /// </summary>
        public static string Welcome_back {
            get {
                return ResourceManager.GetString("Welcome back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What do you want?.
        /// </summary>
        public static string What_do_you_want {
            get {
                return ResourceManager.GetString("What do you want", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winners table.
        /// </summary>
        public static string Winners_table {
            get {
                return ResourceManager.GetString("Winners table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work in progress.
        /// </summary>
        public static string Work_in_progress {
            get {
                return ResourceManager.GetString("Work in progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You already has sent a friend request to this user.
        /// </summary>
        public static string You_already_has_sent_a_friend_request_to_this_user {
            get {
                return ResourceManager.GetString("You already has sent a friend request to this user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are banned!!!!!.
        /// </summary>
        public static string You_are_banned_____ {
            get {
                return ResourceManager.GetString("You are banned!!!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t send a friend request to yourself.
        /// </summary>
        public static string You_can_t_send_a_friend_request_to_yourself {
            get {
                return ResourceManager.GetString("You can\'t send a friend request to yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cant&apos;t send a friend request to this user because is already your friend.
        /// </summary>
        public static string You_cant_t_send_a_friend_request_to_this_user_because_is_already_your_friend {
            get {
                return ResourceManager.GetString("You cant\'t send a friend request to this user because is already your friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been banned!!!!!.
        /// </summary>
        public static string You_have_been_banned_____ {
            get {
                return ResourceManager.GetString("You have been banned!!!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been expelt from the game for being the unique player in the game!.
        /// </summary>
        public static string You_have_been_expelt_from_the_game_for_being_the_unique_player_in_the_game_ {
            get {
                return ResourceManager.GetString("You have been expelt from the game for being the unique player in the game!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been invitated to the lobby!.
        /// </summary>
        public static string You_have_been_invitated_to_the_lobby_ {
            get {
                return ResourceManager.GetString("You have been invitated to the lobby!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Word #.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the word.
        /// </summary>
        public static string WriteWord {
            get {
                return ResourceManager.GetString("WriteWord", resourceCulture);
            }
        }
    }
}
