//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renovación_LIS_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renovación_LIS_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code has been sent to your email.
        /// </summary>
        public static string A_code_has_been_sent_to_your_email {
            get {
                return ResourceManager.GetString("A code has been sent to your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept friend request.
        /// </summary>
        public static string Accept_friend_request {
            get {
                return ResourceManager.GetString("Accept friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account made successfully!!!.
        /// </summary>
        public static string Account_made_successfully {
            get {
                return ResourceManager.GetString("Account made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth date should be before than the actual date.
        /// </summary>
        public static string Birth_date_should_be_before_than_the_actual_date {
            get {
                return ResourceManager.GetString("Birth date should be before than the actual date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth day.
        /// </summary>
        public static string Birth_day {
            get {
                return ResourceManager.GetString("Birth day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel friend request.
        /// </summary>
        public static string Cancel_friend_request {
            get {
                return ResourceManager.GetString("Cancel friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel friendship.
        /// </summary>
        public static string Cancel_friendship {
            get {
                return ResourceManager.GetString("Cancel friendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelation of friend request send made sucessfully.
        /// </summary>
        public static string Cancelation_of_friend_request_send_made_sucessfully {
            get {
                return ResourceManager.GetString("Cancelation of friend request send made sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancellation of sending friend request made successfully!!!.
        /// </summary>
        public static string Cancellation_of_sending_friend_request_made_successfully {
            get {
                return ResourceManager.GetString("Cancellation of sending friend request made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing....
        /// </summary>
        public static string Closing___ {
            get {
                return ResourceManager.GetString("Closing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code for change your password..
        /// </summary>
        public static string Code_for_change_your_password {
            get {
                return ResourceManager.GetString("Code for change your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your new password.
        /// </summary>
        public static string Confirm_your_new_password {
            get {
                return ResourceManager.GetString("Confirm your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date.
        /// </summary>
        public static string Creation_date {
            get {
                return ResourceManager.GetString("Creation date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to exit?.
        /// </summary>
        public static string Do_you_want_to_exit {
            get {
                return ResourceManager.GetString("Do you want to exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email already on use.
        /// </summary>
        public static string Email_already_on_use {
            get {
                return ResourceManager.GetString("Email already on use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email not found.
        /// </summary>
        public static string Email_not_found {
            get {
                return ResourceManager.GetString("Email not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Last Name.
        /// </summary>
        public static string First_Last_Name {
            get {
                return ResourceManager.GetString("First Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend nickname.
        /// </summary>
        public static string Friend_nickname {
            get {
                return ResourceManager.GetString("Friend nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request rejected.
        /// </summary>
        public static string Friend_request_rejected {
            get {
                return ResourceManager.GetString("Friend request rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent succesfully!!!.
        /// </summary>
        public static string Friend_request_sent_succesfully {
            get {
                return ResourceManager.GetString("Friend request sent succesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request successfully accepted!!!.
        /// </summary>
        public static string Friend_request_successfully_accepted {
            get {
                return ResourceManager.GetString("Friend request successfully accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends requests.
        /// </summary>
        public static string Friends_requests {
            get {
                return ResourceManager.GetString("Friends requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship cancellation made successfully.
        /// </summary>
        public static string Friendship_cancellation_made_successfully {
            get {
                return ResourceManager.GetString("Friendship cancellation made successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you already have an account? Log In.
        /// </summary>
        public static string Have_you_already_have_an_account {
            get {
                return ResourceManager.GetString("Have you already have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce the code.
        /// </summary>
        public static string Introduce_the_code {
            get {
                return ResourceManager.GetString("Introduce the code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce this code for change your password: .
        /// </summary>
        public static string Introduce_this_code_for_change_your_password {
            get {
                return ResourceManager.GetString("Introduce this code for change your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce your email.
        /// </summary>
        public static string Introduce_your_email {
            get {
                return ResourceManager.GetString("Introduce your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid code.
        /// </summary>
        public static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid nickname.
        /// </summary>
        public static string Invalid_nickname {
            get {
                return ResourceManager.GetString("Invalid nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation details.
        /// </summary>
        public static string Invitation_details {
            get {
                return ResourceManager.GetString("Invitation details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string Invite_friends {
            get {
                return ResourceManager.GetString("Invite friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string Modify_profile {
            get {
                return ResourceManager.GetString("Modify profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name(s).
        /// </summary>
        public static string Name_s_ {
            get {
                return ResourceManager.GetString("Name(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname already on use.
        /// </summary>
        public static string Nickname_already_on_use {
            get {
                return ResourceManager.GetString("Nickname already on use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not register yet? Sign Up.
        /// </summary>
        public static string NotregisterYet {
            get {
                return ResourceManager.GetString("NotregisterYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed sucessfully!!!.
        /// </summary>
        public static string Password_changed_sucessfully___ {
            get {
                return ResourceManager.GetString("Password changed sucessfully!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile modified successfully!!!.
        /// </summary>
        public static string Profile_modified_successfully___ {
            get {
                return ResourceManager.GetString("Profile modified successfully!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile picture.
        /// </summary>
        public static string Profile_picture {
            get {
                return ResourceManager.GetString("Profile picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject friend request.
        /// </summary>
        public static string Reject_friend_request {
            get {
                return ResourceManager.GetString("Reject friend request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an image.
        /// </summary>
        public static string Select_an_image {
            get {
                return ResourceManager.GetString("Select an image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string Send_code {
            get {
                return ResourceManager.GetString("Send code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send invitation to friend.
        /// </summary>
        public static string Send_invitation_to_friend {
            get {
                return ResourceManager.GetString("Send invitation to friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send message.
        /// </summary>
        public static string Send_message {
            get {
                return ResourceManager.GetString("Send message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show friends invitations.
        /// </summary>
        public static string Show_friends_invitations {
            get {
                return ResourceManager.GetString("Show friends invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success!!!.
        /// </summary>
        public static string Success___ {
            get {
                return ResourceManager.GetString("Success!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname(s).
        /// </summary>
        public static string Surname_s_ {
            get {
                return ResourceManager.GetString("Surname(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file shouldn&apos;t be larger than 1 MB.
        /// </summary>
        public static string The_file_shouldn_t_be_larger_than_1_MB {
            get {
                return ResourceManager.GetString("The file shouldn\'t be larger than 1 MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The introduced nickname doesn&apos;t exists.
        /// </summary>
        public static string The_introduced_nickname_doesn_t_exists {
            get {
                return ResourceManager.GetString("The introduced nickname doesn\'t exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The message shouldn&apos;t have more than 100 characters.
        /// </summary>
        public static string The_message_shouldn_t_have_more_than_100_characters {
            get {
                return ResourceManager.GetString("The message shouldn\'t have more than 100 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password isn&apos;t correct.
        /// </summary>
        public static string The_password_isn_t_correct {
            get {
                return ResourceManager.GetString("The password isn\'t correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords aren&apos;t the same.
        /// </summary>
        public static string The_passwords_aren_t_the_same {
            get {
                return ResourceManager.GetString("The passwords aren\'t the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The text fields with invalid values are: .
        /// </summary>
        public static string The_text_fields_with_invalid_values_are {
            get {
                return ResourceManager.GetString("The text fields with invalid values are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is already logged.
        /// </summary>
        public static string The_user_is_already_logged {
            get {
                return ResourceManager.GetString("The user is already logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you want to sent a friend request doesn&apos;t exists.
        /// </summary>
        public static string The_user_you_want_to_sent_a_friend_request_doesn_t_exists {
            get {
                return ResourceManager.GetString("The user you want to sent a friend request doesn\'t exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To confirm the new password, we&apos;ll send a code to your email.
        /// </summary>
        public static string To_confirm_the_new_password__we_ll_send_a_code_to_your_email {
            get {
                return ResourceManager.GetString("To confirm the new password, we\'ll send a code to your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too Bad!!!.
        /// </summary>
        public static string Too_Bad___ {
            get {
                return ResourceManager.GetString("Too Bad!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome back .
        /// </summary>
        public static string Welcome_back {
            get {
                return ResourceManager.GetString("Welcome back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What do you want?.
        /// </summary>
        public static string What_do_you_want {
            get {
                return ResourceManager.GetString("What do you want", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You already has sent a friend request to this user.
        /// </summary>
        public static string You_already_has_sent_a_friend_request_to_this_user {
            get {
                return ResourceManager.GetString("You already has sent a friend request to this user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t send a friend request to yourself.
        /// </summary>
        public static string You_can_t_send_a_friend_request_to_yourself {
            get {
                return ResourceManager.GetString("You can\'t send a friend request to yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cant&apos;t send a friend request to this user because is already your friend.
        /// </summary>
        public static string You_cant_t_send_a_friend_request_to_this_user_because_is_already_your_friend {
            get {
                return ResourceManager.GetString("You cant\'t send a friend request to this user because is already your friend", resourceCulture);
            }
        }
    }
}
